# Generated by Django 3.1.12 on 2021-06-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(blank=True, default=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, choices=[('B', 'Buy'), ('H', 'Hold'), ('S', 'Sell')], default=True, max_length=1, null=True)),
                ('symbol', models.CharField(blank=True, default=True, max_length=6, null=True)),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('share_price', models.FloatField(blank=True, default=True, null=True)),
                ('share_quant', models.FloatField(blank=True, default=True, null=True)),
                ('share_equity', models.FloatField(blank=True, default=True, null=True)),
                ('roi_total', models.FloatField(blank=True, default=True, null=True)),
                ('roi_net', models.FloatField(blank=True, default=True, null=True)),
                ('avg_buy_price', models.FloatField(blank=True, default=True, null=True)),
                ('testing', models.BooleanField(default=True)),
            ],
        ),
    ]
