# Generated by Django 3.1.12 on 2021-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(blank=True, choices=[('B', 'Buy'), ('H', 'Hold'), ('S', 'Sell')], default=True, max_length=4, null=True),
        ),
    ]
